-- ============================================================================
-- seed-accredited-domains.sql  —  standalone allowlist loader
-- ============================================================================
-- Load a curated set of accredited U.S. institution domains into
-- accredited_domains. Run DIRECTLY with the mysql client (bypasses the
-- migration runner):
--
--     mysql -u <user> -p <database>  <  student-access/seed-accredited-domains.sql
--
-- Idempotent: INSERT IGNORE means re-running never duplicates and never errors
-- on rows that already exist. This is a STARTER breadth set (~150 schools), not
-- exhaustive — use scripts/loadAccreditedDomains.ts to bulk-load the full
-- authoritative list (thousands of institutions).
--
-- Requires the accredited_domains table (migration 021) to already exist.
-- ============================================================================

INSERT IGNORE INTO accredited_domains (domain, institution_name, country, status) VALUES
  -- Ivy League
  ('harvard.edu','Harvard University','US','active'),
  ('yale.edu','Yale University','US','active'),
  ('princeton.edu','Princeton University','US','active'),
  ('columbia.edu','Columbia University','US','active'),
  ('cornell.edu','Cornell University','US','active'),
  ('brown.edu','Brown University','US','active'),
  ('dartmouth.edu','Dartmouth College','US','active'),
  ('upenn.edu','University of Pennsylvania','US','active'),
  -- Leading private research universities
  ('mit.edu','Massachusetts Institute of Technology','US','active'),
  ('stanford.edu','Stanford University','US','active'),
  ('caltech.edu','California Institute of Technology','US','active'),
  ('uchicago.edu','University of Chicago','US','active'),
  ('jhu.edu','Johns Hopkins University','US','active'),
  ('duke.edu','Duke University','US','active'),
  ('northwestern.edu','Northwestern University','US','active'),
  ('vanderbilt.edu','Vanderbilt University','US','active'),
  ('rice.edu','Rice University','US','active'),
  ('emory.edu','Emory University','US','active'),
  ('wustl.edu','Washington University in St. Louis','US','active'),
  ('nd.edu','University of Notre Dame','US','active'),
  ('georgetown.edu','Georgetown University','US','active'),
  ('cmu.edu','Carnegie Mellon University','US','active'),
  ('usc.edu','University of Southern California','US','active'),
  ('nyu.edu','New York University','US','active'),
  ('bu.edu','Boston University','US','active'),
  ('bc.edu','Boston College','US','active'),
  ('northeastern.edu','Northeastern University','US','active'),
  ('tufts.edu','Tufts University','US','active'),
  ('brandeis.edu','Brandeis University','US','active'),
  ('gwu.edu','George Washington University','US','active'),
  ('american.edu','American University','US','active'),
  ('syracuse.edu','Syracuse University','US','active'),
  ('fordham.edu','Fordham University','US','active'),
  ('villanova.edu','Villanova University','US','active'),
  ('smu.edu','Southern Methodist University','US','active'),
  ('tcu.edu','Texas Christian University','US','active'),
  ('baylor.edu','Baylor University','US','active'),
  ('pepperdine.edu','Pepperdine University','US','active'),
  ('wfu.edu','Wake Forest University','US','active'),
  ('lehigh.edu','Lehigh University','US','active'),
  ('bucknell.edu','Bucknell University','US','active'),
  ('rpi.edu','Rensselaer Polytechnic Institute','US','active'),
  ('stevens.edu','Stevens Institute of Technology','US','active'),
  ('rit.edu','Rochester Institute of Technology','US','active'),
  ('drexel.edu','Drexel University','US','active'),
  ('depaul.edu','DePaul University','US','active'),
  ('marquette.edu','Marquette University','US','active'),
  ('gonzaga.edu','Gonzaga University','US','active'),
  ('scu.edu','Santa Clara University','US','active'),
  ('lmu.edu','Loyola Marymount University','US','active'),
  ('miami.edu','University of Miami','US','active'),
  ('tulane.edu','Tulane University','US','active'),
  ('case.edu','Case Western Reserve University','US','active'),
  ('rochester.edu','University of Rochester','US','active'),
  ('wpi.edu','Worcester Polytechnic Institute','US','active'),
  -- University of California system
  ('berkeley.edu','University of California, Berkeley','US','active'),
  ('ucla.edu','University of California, Los Angeles','US','active'),
  ('ucsd.edu','University of California, San Diego','US','active'),
  ('uci.edu','University of California, Irvine','US','active'),
  ('ucdavis.edu','University of California, Davis','US','active'),
  ('ucsb.edu','University of California, Santa Barbara','US','active'),
  ('ucr.edu','University of California, Riverside','US','active'),
  ('ucsc.edu','University of California, Santa Cruz','US','active'),
  ('ucmerced.edu','University of California, Merced','US','active'),
  -- California State University (major campuses)
  ('sdsu.edu','San Diego State University','US','active'),
  ('sjsu.edu','San Jose State University','US','active'),
  ('calpoly.edu','California Polytechnic State University, San Luis Obispo','US','active'),
  ('csulb.edu','California State University, Long Beach','US','active'),
  ('fullerton.edu','California State University, Fullerton','US','active'),
  ('sfsu.edu','San Francisco State University','US','active'),
  ('csun.edu','California State University, Northridge','US','active'),
  -- Public flagships & major state universities
  ('umich.edu','University of Michigan','US','active'),
  ('msu.edu','Michigan State University','US','active'),
  ('umn.edu','University of Minnesota','US','active'),
  ('wisc.edu','University of Wisconsin-Madison','US','active'),
  ('illinois.edu','University of Illinois Urbana-Champaign','US','active'),
  ('indiana.edu','Indiana University','US','active'),
  ('purdue.edu','Purdue University','US','active'),
  ('osu.edu','The Ohio State University','US','active'),
  ('psu.edu','Pennsylvania State University','US','active'),
  ('pitt.edu','University of Pittsburgh','US','active'),
  ('temple.edu','Temple University','US','active'),
  ('rutgers.edu','Rutgers University','US','active'),
  ('umd.edu','University of Maryland','US','active'),
  ('virginia.edu','University of Virginia','US','active'),
  ('vt.edu','Virginia Tech','US','active'),
  ('gmu.edu','George Mason University','US','active'),
  ('vcu.edu','Virginia Commonwealth University','US','active'),
  ('jmu.edu','James Madison University','US','active'),
  ('odu.edu','Old Dominion University','US','active'),
  ('unc.edu','University of North Carolina at Chapel Hill','US','active'),
  ('ncsu.edu','North Carolina State University','US','active'),
  ('utexas.edu','University of Texas at Austin','US','active'),
  ('tamu.edu','Texas A&M University','US','active'),
  ('uh.edu','University of Houston','US','active'),
  ('utdallas.edu','University of Texas at Dallas','US','active'),
  ('utsa.edu','University of Texas at San Antonio','US','active'),
  ('unt.edu','University of North Texas','US','active'),
  ('ttu.edu','Texas Tech University','US','active'),
  ('ufl.edu','University of Florida','US','active'),
  ('fsu.edu','Florida State University','US','active'),
  ('ucf.edu','University of Central Florida','US','active'),
  ('usf.edu','University of South Florida','US','active'),
  ('fiu.edu','Florida International University','US','active'),
  ('fau.edu','Florida Atlantic University','US','active'),
  ('uga.edu','University of Georgia','US','active'),
  ('gatech.edu','Georgia Institute of Technology','US','active'),
  ('gsu.edu','Georgia State University','US','active'),
  ('clemson.edu','Clemson University','US','active'),
  ('sc.edu','University of South Carolina','US','active'),
  ('uw.edu','University of Washington','US','active'),
  ('wsu.edu','Washington State University','US','active'),
  ('uoregon.edu','University of Oregon','US','active'),
  ('oregonstate.edu','Oregon State University','US','active'),
  ('arizona.edu','University of Arizona','US','active'),
  ('asu.edu','Arizona State University','US','active'),
  ('colorado.edu','University of Colorado Boulder','US','active'),
  ('colostate.edu','Colorado State University','US','active'),
  ('ku.edu','University of Kansas','US','active'),
  ('k-state.edu','Kansas State University','US','active'),
  ('missouri.edu','University of Missouri','US','active'),
  ('uiowa.edu','University of Iowa','US','active'),
  ('iastate.edu','Iowa State University','US','active'),
  ('unl.edu','University of Nebraska-Lincoln','US','active'),
  ('ou.edu','University of Oklahoma','US','active'),
  ('okstate.edu','Oklahoma State University','US','active'),
  ('utah.edu','University of Utah','US','active'),
  ('byu.edu','Brigham Young University','US','active'),
  ('unm.edu','University of New Mexico','US','active'),
  ('uky.edu','University of Kentucky','US','active'),
  ('louisville.edu','University of Louisville','US','active'),
  ('lsu.edu','Louisiana State University','US','active'),
  ('olemiss.edu','University of Mississippi','US','active'),
  ('msstate.edu','Mississippi State University','US','active'),
  ('ua.edu','University of Alabama','US','active'),
  ('auburn.edu','Auburn University','US','active'),
  ('utk.edu','University of Tennessee, Knoxville','US','active'),
  ('memphis.edu','University of Memphis','US','active'),
  ('uark.edu','University of Arkansas','US','active'),
  ('wvu.edu','West Virginia University','US','active'),
  ('uconn.edu','University of Connecticut','US','active'),
  ('umass.edu','University of Massachusetts Amherst','US','active'),
  ('unh.edu','University of New Hampshire','US','active'),
  ('uvm.edu','University of Vermont','US','active'),
  ('maine.edu','University of Maine','US','active'),
  ('uri.edu','University of Rhode Island','US','active'),
  ('udel.edu','University of Delaware','US','active'),
  -- SUNY system (major campuses)
  ('buffalo.edu','University at Buffalo (SUNY)','US','active'),
  ('stonybrook.edu','Stony Brook University (SUNY)','US','active'),
  ('binghamton.edu','Binghamton University (SUNY)','US','active'),
  ('albany.edu','University at Albany (SUNY)','US','active'),
  ('wayne.edu','Wayne State University','US','active');
